### PR TITLE
Don't fail the build if verification fails against a pending pact.

### LINKED ISSUE #51: `VerificationResult.Failed` should not cause tests to fail if the pact is pending
https://github.com/jbwheatley/pact4s/blob/main/shared/src/main/scala/pact4s/PactVerifyResources.scala#L37

This needs to check the status of `failed.getPending`. If it's true, we should mark the test as `skipped` instead of `failure`, since pending pacts should not fail the build.

Originally filed as https://github.com/pact-foundation/pact-jvm/issues/1417

### PR DESCRIPTION
**Pull request by kflorence**
Fixes #51

This also includes the [sbt-ide-settings](https://github.com/JetBrains/sbt-ide-settings) plugin and configures the project so that when it is imported into the IntelliJ IDE it will exclude Scala 2.12 and Java 8 dependencies and projects. This prevents classpath conflicts (e.g. the same classes existing in 4 different contexts) and allows for a normal development experience (including the ability to run and debug tests from the IDE).

### CODE REVIEW

File: munit-cats-effect-pact/src/main/scala/pact4s/munit/PactVerifier.scala [hunk 1]
```diff
@@ -21,6 +21,7 @@ import pact4s.PactVerifyResources
 import sourcecode.{File, FileName, Line}
 
 trait PactVerifier extends Assertions with PactVerifyResources {
+  override private[pact4s] def skip(message: String)(implicit fileName: FileName, file: File, line: Line): Unit = ()
```
Comment (kflorence) [inline munit-cats-effect-pact/src/main/scala/pact4s/munit/PactVerifier.scala:24]: @jbwheatley it doesn't look like MUnit has the concept of "skip" or "cancel" -- any idea what to do here?

Comment (jbwheatley) [reply munit-cats-effect-pact/src/main/scala/pact4s/munit/PactVerifier.scala:24]: hmm, maybe the best we can do is just log a message in this case

Comment (kflorence) [reply munit-cats-effect-pact/src/main/scala/pact4s/munit/PactVerifier.scala:24]: yeah, i thought so too... although I don't think we have a unified logger yet, do we?

Comment (jbwheatley) [reply munit-cats-effect-pact/src/main/scala/pact4s/munit/PactVerifier.scala:24]: You can change `PactVerifyResources` to extend `trait Pact4sLogger` to get access to a logger

Comment (jbwheatley) [reply munit-cats-effect-pact/src/main/scala/pact4s/munit/PactVerifier.scala:24]: I think possibly Munit could be done with `assume(cond = false, message)`. Worth a try

Comment (kflorence) [reply munit-cats-effect-pact/src/main/scala/pact4s/munit/PactVerifier.scala:24]: Looks right https://scalameta.org/munit/docs/filtering.html#ignore-single-test-case-based-on-a-dynamic-conditions

**Comment by kflorence** [comment]
Examples of test output.

# MUnit
```
pact4s.munit.PendingPactVerificationTestSuite:
  + pending pact failure should be skipped 0.275s
[info] Passed: Total 1, Failed 0, Errors 0, Passed 1
[success] Total time: 5 s, completed Sep 11, 2021, 5:28:05 PM
```

Looks like `MUnit` doesn't log anything when a test is skipped, just marks it as passed. Maybe this is a common/okay expectation for that library? If not, we could add some logs ourselves, but it seems strange that the library wouldn't do that itself.

# Scalatest
```
[info] PendingPactVerificationTestSuite:
[info] pending pact failure
[info] - should be skipped !!! CANCELED !!!
[info]   Verification failed [PENDING]: "description" (PendingPactVerificationTestSuite.scala:6)
[info] Run completed in 3 seconds, 86 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 1, ignored 0, pending 0
[info] No tests were executed.
[success] Total time: 8 s, completed Sep 11, 2021, 5:28:38 PM
```

# Weaver
```
[info] pact4s.weaver.PendingPactVerificationTestSuite
[info] - pending pact failure should be skipped 253ms !!! CANCELLED !!!
[info]   Verification failed [PENDING]: "description" (PendingPactVerificationTestSuite.scala:7)
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0, Canceled 1
[success] Total time: 9 s, completed Sep 11, 2021, 5:33:16 PM
```
